reventureEndingOffset = 900271000

location_table = {
    '22: Paperweight': reventureEndingOffset+1,
    '26: Greedy Bastard': reventureEndingOffset+2,
    '31: Collateral Damage': reventureEndingOffset+3,
    '16: Monster Hunter': reventureEndingOffset+4,
    '62: Jackpot': reventureEndingOffset+5,
    '12: Hobbies': reventureEndingOffset+6,
    '06: The Floor is Lava': reventureEndingOffset+7,
    '46: Extreme Sports': reventureEndingOffset+8,
    '54: Paraphilia': reventureEndingOffset+9,
    '10: Gold Rush': reventureEndingOffset+10,
    '17: Public Transport Next Time': reventureEndingOffset+11,
    '28: Don\'t Try This at Home': reventureEndingOffset+12,
    '14: Dracar-ish': reventureEndingOffset+13,
    '43: Dinner for Two': reventureEndingOffset+14,
    '51: Politics': reventureEndingOffset+15,
    '78: Silver or Lead': reventureEndingOffset+16,
    '20: Day Off': reventureEndingOffset+17,
    '01: It\'s Dangerous to be Near Tim': reventureEndingOffset+18,
    '73: Dark Love': reventureEndingOffset+19,
    '07: Go Swimming': reventureEndingOffset+20,
    '34: -1st Floor': reventureEndingOffset+21,
    '21: You Nailed It': reventureEndingOffset+22,
    '33: Leap of Faith': reventureEndingOffset+23,
    '42: Sneaky Bastard': reventureEndingOffset+24,
    '72: Ecologist': reventureEndingOffset+25,
    '32: You Monster': reventureEndingOffset+26,
    '08: Roll & Rock': reventureEndingOffset+27,
    '38: Oh Boy, I\'m so Hungry': reventureEndingOffset+28,
    '24: Strawberry': reventureEndingOffset+29,
    '66: Finite War': reventureEndingOffset+30,
    '58: Dark Extreme Sports': reventureEndingOffset+31,
    '27: Airstrike': reventureEndingOffset+32,
    '56: Refund Request': reventureEndingOffset+33,
    '84: Not what you Expected': reventureEndingOffset+34,
    '53: Videogames': reventureEndingOffset+35,
    '04: Public Enemy': reventureEndingOffset+36,
    '57: Friendzoned': reventureEndingOffset+37,
    '40: Sexy Beard': reventureEndingOffset+38,
    '37: Free Hugs': reventureEndingOffset+39,
    '19: Broken Heart': reventureEndingOffset+40,
    '11: Feline Company': reventureEndingOffset+41,
    '64: I Thought It Was A Mimic': reventureEndingOffset+42,
    '55: Escape Shortcut': reventureEndingOffset+43,
    '50: P0wned': reventureEndingOffset+44,
    '69: Quick and Dirty': reventureEndingOffset+45,
    '93: Dark Delivery Boy': reventureEndingOffset+46,
    '36: Fireproof': reventureEndingOffset+47,
    '86: Full House': reventureEndingOffset+48,
    '92: First Date': reventureEndingOffset+49,
    '09: Customer is Always Right': reventureEndingOffset+50,
    '05: Kingslayer': reventureEndingOffset+51,
    '18: King of Hearts': reventureEndingOffset+52,
    '03: Please Nerf This': reventureEndingOffset+53,
    '13: Allergic to Cuteness': reventureEndingOffset+54,
    '90: Try Harder': reventureEndingOffset+55,
    '82: Perfect Crime': reventureEndingOffset+56,
    '29: The Man in the Steel Mask': reventureEndingOffset+57,
    '41: Post-Traumatic Stress Disorder': reventureEndingOffset+58,
    '23: True Beauty is inside': reventureEndingOffset+59,
    '74: Bittersweet Revenge': reventureEndingOffset+60,
    '87: Crunch Hell': reventureEndingOffset+61,
    '45: Well Excuuuuse Me, Princess': reventureEndingOffset+62,
    '60: Viva La Resistance': reventureEndingOffset+63,
    '25: Bully': reventureEndingOffset+64,
    '47: Harakiri': reventureEndingOffset+65,
    '48: It\'s my First Day': reventureEndingOffset+66,
    '52: I\'m Feeling Lucky': reventureEndingOffset+67,
    '49: Victory Royale': reventureEndingOffset+68,
    '44: Bad Leverage': reventureEndingOffset+69,
    '15: Family Gathering': reventureEndingOffset+70,
    '35: Wastewater': reventureEndingOffset+71,
    '68: Otaku Fever': reventureEndingOffset+72,
    '75: Please, Not Again': reventureEndingOffset+73,
    '88: Odyssey': reventureEndingOffset+74,
    '02: Shit Happens': reventureEndingOffset+75,
    '91: Jump Around': reventureEndingOffset+76,
    '39: Everything is Terrible': reventureEndingOffset+77,
    '94: Influencers': reventureEndingOffset+78,
    '30: Subliminal Message': reventureEndingOffset+79,
    '61: Syndicalism': reventureEndingOffset+80,
    '80: Chicken of Doom': reventureEndingOffset+81,
    '83: We Have to Go Back': reventureEndingOffset+82,
    '97: Swimming Into the Sunset': reventureEndingOffset+83,
    '98: Suspension Points': reventureEndingOffset+84,
    '95: Hypothermia': reventureEndingOffset+85,
    '89: Intestinal Parasites': reventureEndingOffset+86,
    '96: Pirates': reventureEndingOffset+87,
    '67: Stay Determined': reventureEndingOffset+88,
    '85: Hey, Listen': reventureEndingOffset+89,
    '65: Overheal': reventureEndingOffset+90,
    '63: You Don\'t Mess With Chicken': reventureEndingOffset+91,
    '79: Good Ending': reventureEndingOffset+92,
    '76: A Waifu is You': reventureEndingOffset+93,
    '77: Battle Royale': reventureEndingOffset+94,
    '70: It\'s a Trap': reventureEndingOffset+95,
    '59: Away From Kingdom': reventureEndingOffset+96,
    '81: Forever Together': reventureEndingOffset+97,
    '99: Delivery Boy': reventureEndingOffset+98,
    '71: Sustainable Development': reventureEndingOffset+99,
    '100: The End': None,
    'Event Kill Juan': None,
    'Event Kill Miguel': None,
    'Event Kill Javi': None,
    'Event Kill Alberto': None,
    'Event Kill Daniel': None,
}